### ISSUE TITLE
Question: is this Windows - compatible?

### ISSUE THREAD

**Issue by YurySolovyov** [kemitchell/native-readdir.js#4]
I didn't found any info about windows compatibility in readme.

**Comment by mrmlnc** [comment]
Nope, https://github.com/kemitchell/native-readdir.js/blob/master/package.json#L22-L24

``` json
  "os": [
    "!win32"
  ],
```

**Comment by DomVinyard** [comment]
That means Win32 though right? What about windows 10/API?
