### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by DomVinyard** [kemitchell/native-readdir.js#5]
Over Christmas I'm going to do a little reading to determine how plausible it is to get this project working with Windows. 

I probably wouldn't be writing the bulk of the code myself because I have no C++ experience but if I can find a plausible approach I will try and find(/bribe) someone with the requisite skills.

@kemitchell would you welcome a PR to that effect?

My initial foray into researching this issue led me to here, and I wonder if this would form the basis: 

https://github.com/tronkko/dirent

Any info, or comments, or help, or advice would be very, very welcome

**Comment by kemitchell** [comment]
Nothing against Windows, except I don't use it or target it in any of my software work.

This tiny package is a thin wrapper around the POSIX directory entry streaming API. The natural place for a thin wrapper around a Windows directory entry streaming API would be another tiny, standalone package.

If folks want a cross-platform `npm i $something` to stream directory entries, they can write one to `require` and wrap the relevant low-level, platform-specific packages. There are analogous packages for filesystem event watching and other interfaces that vary between Unix-like systems.

**Comment by DomVinyard** [comment]
> Nothing against Windows, except I don't use it or target it in any of my software work.

Amen, if it were up to me neither would I.

> The natural place for a thin wrapper around a Windows directory entry streaming API would be another tiny, standalone package.

I have a feeling you're correct. Windows uses [FindNextFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364428(v=vs.85).aspx), however the [Windows dirent](https://github.com/tronkko/dirent) project I linked above wraps FindNextFile with readdir(3) so I'm postulating that if it were configured and included into the module correctly your code should technically work out of the box. It would see windows as being unix-like.

**Comment by kemitchell** [comment]
I'm not against readdir on Windows. But I'm not going to put any significant effort into it myself. Those who need it should go build it.

**Comment by DomVinyard** [comment]
Oh absolutely, totally understand - I will continue to look into it. Do you think you could leave this open as a feature-request incase somebody with more talent than me stumbles across it in the meantime and fancies taking it on?
